### ISSUE TITLE
ledger-app-hns not working with Ledger Version 1.6.1

### ISSUE THREAD

**Issue by Jay991** [handshake-org/ledger-app-hns#6]
I'm running on Ubuntu 20.04.1 LTS, Ledger version 1.6.1, python 3.8, with ledgerblue installed.

After running the below successfully:
```
$ git clone https://github.com/handshake-org/ledger-app-hns.git
$ cd ledger-app-hns
$ docker build --build-arg CACHE_BUST="$(date)" -f Dockerfile.build -t ledger-app-hns-build .
```

I get the below response when I run: 
`$ docker build --build-arg CACHE_BUST="$(date)" -f Dockerfile.build -t ledger-app-hns-build .`
getting the below response (keys have been obsecured) 

```
$ sudo docker run --rm --privileged ledger-app-hns-build make load

TARGET_NAME=TARGET_NANOS TARGET_ID=0x31100004 TARGET_VERSION=1.6.0
make: arm-none-eabi-gcc: Command not found
BOLOS_ENV=/bolos-devenv
BOLOS_ENV=/bolos-devenv
find: '/nanos-secure-sdk/lib_ux/glyphs/': No such file or directory
GIT_REF is set to og-1.6.0-1
python -m ledgerblue.loadApp --curve secp256k1 --tlv --targetId 0x31100004 --targetVersion="1.6.0" --delete --fileName bin/app.hex --appName "Handshake" --appVersion 1.0.0 --dataSize $((0x`cat debug/app.map |grep _envram_data | tr -s ' ' | cut -f2 -d' '|cut -f2 -d'x'` - 0x`cat debug/app.map |grep _nvram_data | tr -s ' ' | cut -f2 -d' '|cut -f2 -d'x'`)) `ICONHEX=\`python3 /nanos-secure-sdk/icon3.py --hexbitmaponly nanos_icon_hns.gif  2>/dev/null\` ; [ ! -z "$ICONHEX" ] && echo "--icon $ICONHEX"`  --appFlags 0x50 --path ""
Generated random root public key : b'04bda46a833cdafb3708ed99c6e1ea826357ea5f82083e6bb69271ea230bf139ef3df47bd37988d2b14e9ae4e2f67b52f02ae5b60f3432327b9fd0f125eb35c62b'
Using test master key b'04bda46aed99c6e1ea82635833cdafb37087e4e9ae4e2f67b52f02ae5b60f3432327b9fd0a5f829271ea230bf139ef3df47bd37988d2b1f125e083e6bb6b35c62b' 
Using ephemeral key b'04a172c1bf40508c264e30d5468fa932ad60cd9cd82a1f1745caa09f61499ffecbafc5d52dfdec6b08c41cc5f654984e8c9d4cc819e234909607ed1f8dd12de12d'
Broken certificate chain - loading from user key
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ledgerblue/loadApp.py", line 281, in <module>
    loader.createApp(code_length, args.dataSize, paramsSize, args.appFlags, args.bootAddr|1)
  File "/usr/local/lib/python3.5/dist-packages/ledgerblue/hexLoader.py", line 359, in createApp
    self.exchange(self.cla, 0x00, 0x00, 0x00, data)
  File "/usr/local/lib/python3.5/dist-packages/ledgerblue/hexLoader.py", line 201, in exchange
    return self.scpUnwrap(bytes(self.card.exchange(apdu)))
  File "/usr/local/lib/python3.5/dist-packages/ledgerblue/comm.py", line 145, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6a84 (Not enough space?)
make: *** [load] Error 1
```

**Comment by pinheadmz** [comment]
Closing this because it is outdated. Ledger is in final official testing now. Also see https://github.com/handshake-org/ledger-app-hns/issues/5#issuecomment-881476413
